{
 "title": "BBOX performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Codigos de respuesta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-bbox.codes.200"
    }
   ]
  },
  {
   "title": "Latencia media",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-bbox.latency.median"
    },
    {
     "target": "alias(stats.gauges.artillery-bbox.latency.p95, 'p95')"
    },
    {
     "target": "alias(stats.gauges.artillery-bbox.latency.p99, 'p99')"
    }
   ]
  },
  {
   "title": "Concurrencia",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-bbox.concurrency"
    }
   ]
  }
 ]
}