{
 "title": "Hernan",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-node" },
   {
    "name": "container",
    "query": "1c21-tp-1_node_1, 1c21-tp-1_node_2, 1c21-tp-1_node_3, 1c21-tp-1_cadvisor_1, 1c21-tp-1_grafana_1, 1c21-tp-1_graphite_1,  1c21-tp-1_nginx_1, 1c21-tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency p95 p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.artillery-node.latency.p95, 'P95')"
    },
    {
     "target": "alias(stats.gauges.artillery-node.latency.p99, 'P99')"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-node.rps.count"
    }
   ]
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.artillery-node.errors.*"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.*.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "aliasColors": { "Memory": "#EAB839" },
     "dashLength": 10,
     "fieldConfig": {
      "defaults": {
       "custom": {}
      },
      "overrides": []
     },
     "fill": 1,
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "height": "250px",
     "id": 1,
     "legend": {
      "alignAsTable": true,
      "avg": true,
      "current": true,
      "hideEmpty": true,
      "hideZero": false,
      "max": true,
      "min": false,
      "rightSide": true,
      "show": true,
      "sideWidth": 250,
      "total": false,
      "values": true
     },
     "linewidth": 1,
     "nullPointMode": "connected",
     "options": {
      "alertThreshold": true
     },
     "pointradius": 5,
     "renderer": "flot",
     "seriesOverrides": [
      {
       "alias": "asPercent(stats.gauges.cadvisor.1c21-tp-1_node_1.memory_usage, 1952000000)",
       "yaxis": 1
      },
      {
       "alias": "stats.gauges.cadvisor.1c21-tp-1_gunicorn_1.rx_errors",
       "yaxis": 2
      },
      {
       "alias": "stats.gauges.cadvisor.1c21-tp-1_gunicorn_1.tx_errors",
       "yaxis": 2
      }
     ],
     "spaceLength": 10,
     "targets": [
      {
       "hide": false,
       "refCount": 0,
       "refId": "C",
       "target": "stats.gauges.artillery-node.errors.*",
       "textEditor": false
      }
     ],
     "title": "Errors",
     "tooltip": {
      "shared": true,
      "sort": 0,
      "value_type": "individual"
     },
     "type": "graph",
     "xaxis": {
      "buckets": null,
      "mode": "time",
      "name": null,
      "show": true,
      "values": []
     },
     "yaxes": [
      {
       "format": "none",
       "label": null,
       "logBase": 1,
       "max": null,
       "min": "0",
       "show": true
      },
      {
       "format": "Bps",
       "label": null,
       "logBase": 1,
       "max": null,
       "min": null,
       "show": true
      }
     ],
     "yaxis": {
      "align": false,
      "alignLevel": null
     }
    }
   ]
  }
 ]
}